# Generated by Django 2.2.5 on 2020-01-20 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_review_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.CharField(choices=[('0', 'Excellent'), ('1', 'Good'), ('2', 'Average'), ('3', 'Poor'), ('4', 'Terrible')], max_length=32),
        ),
        migrations.AlterField(
            model_name='review',
            name='type',
            field=models.CharField(choices=[('0', 'Families'), ('1', 'Couples'), ('2', 'Solo'), ('3', 'Business'), ('4', 'Friends')], max_length=32),
        ),
    ]
