# Generated by Django 2.2.5 on 2020-01-05 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20200105_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[{1: '1', 2: '2'}], default=1, max_length=32),
            preserve_default=False,
        ),
    ]
