# Generated by Django 2.2.5 on 2020-01-05 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_review_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[('0', 'Empty submissions'), ('1', 'Incomplete submissions'), ('2', 'Complete submissions')], default='available', max_length=32),
        ),
    ]
