# Generated by Django 2.2.5 on 2020-01-05 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20200105_1946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='type',
        ),
        migrations.AlterField(
            model_name='review',
            name='status',
            field=models.CharField(blank=True, choices=[('0', 'Families'), ('1', 'Couples'), ('2', 'Solo'), ('3', 'Business'), ('4', 'Friends')], max_length=32),
        ),
    ]
