# Generated by Django 2.2.5 on 2020-01-05 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_auto_20200105_1953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='status',
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.CharField(blank=True, choices=[('0', 'Excellent'), ('1', 'Good'), ('2', 'Average'), ('3', 'Poor'), ('4', 'Terrible')], max_length=32),
        ),
    ]
