# Generated by Django 2.2.5 on 2020-03-05 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
        ('reviews', '0015_auto_20200305_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='hotels',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotels.Hotel'),
        ),
        migrations.AlterField(
            model_name='review',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='destinations.Destination'),
        ),
    ]
