# Generated by Django 2.2.5 on 2020-03-05 21:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0016_auto_20200305_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='date_of_visit',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
