# Generated by Django 2.2.5 on 2020-03-07 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0017_review_date_of_visit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='destination',
        ),
    ]
