# Generated by Django 2.2.5 on 2020-03-07 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0017_auto_20200307_1632'),
        ('reviews', '0018_remove_review_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='destinations.Destination'),
        ),
    ]
