# Generated by Django 2.2.5 on 2020-03-05 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0003_destination_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='country',
        ),
    ]
