# Generated by Django 2.2.5 on 2020-03-06 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0006_destination_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='close_timing',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='location',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='open_timing',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='peak_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='DestinationImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='destination-images')),
                ('destination', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='destination_images', to='destinations.Destination')),
            ],
        ),
    ]
