# Generated by Django 2.2.5 on 2020-03-06 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0007_auto_20200306_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='close_timing',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='open_timing',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
