# Generated by Django 2.2.5 on 2020-03-06 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0010_auto_20200306_2046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='contact',
        ),
    ]
