# Generated by Django 2.2.5 on 2020-03-06 20:49

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0011_remove_destination_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='contact',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, unique=True),
        ),
    ]
