# Generated by Django 2.2.5 on 2020-03-07 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0012_destination_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='contact',
        ),
    ]
