# Generated by Django 2.2.5 on 2020-03-07 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities_light', '0008_city_timezone'),
        ('destinations', '0015_auto_20200307_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('category', models.CharField(choices=[('SP', 'Shopping'), ('NP', 'Nature & Parks'), ('MS', 'Museums'), ('LA', 'Landmarks'), ('MN', 'Monuments'), ('AG', 'Art Galleries'), ('WA', 'Water & Amusement Parks')], max_length=100)),
                ('description', models.TextField(blank=True)),
                ('open_timing', models.TimeField(blank=True, null=True)),
                ('close_timing', models.TimeField(blank=True, null=True)),
                ('peak_time', models.TimeField(blank=True, null=True)),
                ('location', models.URLField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='cities_light.City')),
            ],
        ),
        migrations.CreateModel(
            name='DestinationImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='destination-images')),
                ('destination', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='destination_images', to='destinations.Destination')),
            ],
        ),
    ]
