# Generated by Django 2.2.5 on 2020-03-07 16:32

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0016_destination_destinationimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='contact',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, unique=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
