# Generated by Django 2.2.5 on 2020-03-08 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amenity', '0003_amenity_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amenity',
            name='user',
        ),
    ]
