# Generated by Django 2.2.5 on 2020-03-05 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RestaurantImage',
            new_name='TransportImage',
        ),
    ]
