# Generated by Django 2.2.5 on 2020-03-05 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('amenity', '0002_amenity_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('location', models.URLField()),
                ('hotel_class', models.CharField(max_length=50)),
                ('languages', models.CharField(max_length=500)),
                ('style', models.CharField(max_length=500)),
                ('rooms', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('amenities', models.ManyToManyField(to='amenity.Amenity')),
            ],
        ),
    ]
