# Generated by Django 2.2.5 on 2020-03-05 21:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('amenity', '0002_amenity_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('location', models.URLField()),
                ('hotel_class', models.CharField(max_length=50)),
                ('languages', models.CharField(max_length=500)),
                ('style', models.CharField(max_length=500)),
                ('rooms', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('website', models.URLField(blank=True)),
                ('contact', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('amenities', models.ManyToManyField(to='amenity.Amenity')),
                ('liked', models.ManyToManyField(blank=True, related_name='restaurant_liked', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='restaurant-images')),
                ('restaurant', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_images', to='restaurants.Restaurant')),
            ],
        ),
    ]
