# Generated by Django 2.2.5 on 2020-03-10 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_post_destination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='destinations.Destination'),
        ),
    ]
