# Generated by Django 2.2.5 on 2020-03-10 13:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_remove_post_message_html'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='liked',
            field=models.ManyToManyField(blank=True, null=True, related_name='post_liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
