# Generated by Django 2.2.5 on 2020-03-10 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_auto_20200310_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.FileField(blank=True, upload_to='post-files'),
        ),
    ]
